### ISSUE TITLE
update jackson version: 2.2.2 -> 2.6.4

### ISSUE THREAD

**Issue by atsu85** [raphaeljolivet/java2typescript#26]
there is a runtime error when project uses java2typescript-jackson to generate TypeScript, but project uses jackon-databind 2.5 (or newer) at runtime

```
Exception in thread "main" java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.introspect.AnnotatedMethod.<init>(Ljava/lang/reflect/Method;Lcom/fasterxml/jackson/databind/introspect/AnnotationMap;[Lcom/fasterxml/jackson/databind/introspect/AnnotationMap;)V
	at java2typescript.jackson.module.visitors.TSJsonObjectFormatVisitor.addMethod(TSJsonObjectFormatVisitor.java:118)
	at java2typescript.jackson.module.visitors.TSJsonObjectFormatVisitor.addPublicMethods(TSJsonObjectFormatVisitor.java:98)
	at java2typescript.jackson.module.visitors.TSJsonFormatVisitorWrapper.useNamedClassOrParse(TSJsonFormatVisitorWrapper.java:92)
	at java2typescript.jackson.module.visitors.TSJsonFormatVisitorWrapper.expectObjectFormat(TSJsonFormatVisitorWrapper.java:117)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.acceptJsonFormatVisitor(BeanSerializerBase.java:789)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.acceptJsonFormatVisitor(DefaultSerializerProvider.java:409)
	at com.fasterxml.jackson.databind.ObjectMapper.acceptJsonFormatVisitor(ObjectMapper.java:3519)
	at com.fasterxml.jackson.databind.ObjectMapper.acceptJsonFormatVisitor(ObjectMapper.java:3498)
	at java2typescript.jackson.module.DefinitionGenerator.generateTypeScript(DefinitionGenerator.java:54)
	at ee.iglu.killer.java2typescript.TypeScriptDefinitionsGenerator.generateTypeScriptModule(TypeScriptDefinitionsGenerator.java:57)
	at ee.iglu.killer.java2typescript.TypeScriptDefinitionsGenerator.generate(TypeScriptDefinitionsGenerator.java:48)
	at ee.iglu.killer.java2typescript.TypeScriptDefinitionsGenerator.main(TypeScriptDefinitionsGenerator.java:32)

```

This is caused by a api change in jackson-databind com.fasterxml.jackson.databind.introspect.AnnotatedMethod

**Comment by atsu85** [comment]
i'll send the pull request
