### ISSUE TITLE
Maven fails with java.util.EmptyStackException

### ISSUE THREAD

**Issue by red61wjt** [raphaeljolivet/java2typescript#44]
---------------------------------------------------
constituent[0]: file:/home/username/opt/apache-maven-3.2.3/lib/guava-14.0.1.jar
constituent[1]: file:/home/username/opt/apache-maven-3.2.3/lib/log4j-api-2.0-beta6.jar
constituent[2]: file:/home/username/opt/apache-maven-3.2.3/lib/commons-io-2.2.jar
constituent[3]: file:/home/username/opt/apache-maven-3.2.3/lib/aopalliance-1.0.jar
constituent[4]: file:/home/username/opt/apache-maven-3.2.3/lib/maven-settings-3.2.3.jar
constituent[5]: file:/home/username/opt/apache-maven-3.2.3/lib/aether-api-0.9.0.M2.jar
constituent[6]: file:/home/username/opt/apache-maven-3.2.3/lib/wagon-file-2.6.jar
constituent[7]: file:/home/username/opt/apache-maven-3.2.3/lib/aether-connector-wagon-0.9.0.M2.jar
constituent[8]: file:/home/username/opt/apache-maven-3.2.3/lib/maven-model-3.2.3.jar
constituent[9]: file:/home/username/opt/apache-maven-3.2.3/lib/cdi-api-1.0.jar
constituent[10]: file:/home/username/opt/apache-maven-3.2.3/lib/org.eclipse.sisu.plexus-0.0.0.M5.jar
constituent[11]: file:/home/username/opt/apache-maven-3.2.3/lib/commons-cli-1.2.jar
constituent[12]: file:/home/username/opt/apache-maven-3.2.3/lib/sisu-guice-3.1.3-no_aop.jar
constituent[13]: file:/home/username/opt/apache-maven-3.2.3/lib/maven-aether-provider-3.2.3.jar
constituent[14]: file:/home/username/opt/apache-maven-3.2.3/lib/aether-spi-0.9.0.M2.jar
constituent[15]: file:/home/username/opt/apache-maven-3.2.3/lib/log4j-core-2.0-beta6.jar
constituent[16]: file:/home/username/opt/apache-maven-3.2.3/lib/maven-settings-builder-3.2.3.jar
constituent[17]: file:/home/username/opt/apache-maven-3.2.3/lib/maven-plugin-api-3.2.3.jar
constituent[18]: file:/home/username/opt/apache-maven-3.2.3/lib/aether-impl-0.9.0.M2.jar
constituent[19]: file:/home/username/opt/apache-maven-3.2.3/lib/maven-repository-metadata-3.2.3.jar
constituent[20]: file:/home/username/opt/apache-maven-3.2.3/lib/javax.inject-1.jar
constituent[21]: file:/home/username/opt/apache-maven-3.2.3/lib/aether-util-0.9.0.M2.jar
constituent[22]: file:/home/username/opt/apache-maven-3.2.3/lib/plexus-utils-3.0.17.jar
constituent[23]: file:/home/username/opt/apache-maven-3.2.3/lib/maven-compat-3.2.3.jar
constituent[24]: file:/home/username/opt/apache-maven-3.2.3/lib/slf4j-ext-1.7.5.jar
constituent[25]: file:/home/username/opt/apache-maven-3.2.3/lib/org.eclipse.sisu.inject-0.0.0.M5.jar
constituent[26]: file:/home/username/opt/apache-maven-3.2.3/lib/jsr250-api-1.0.jar
constituent[27]: file:/home/username/opt/apache-maven-3.2.3/lib/log4j-slf4j-impl-2.0-beta6.jar
constituent[28]: file:/home/username/opt/apache-maven-3.2.3/lib/maven-model-builder-3.2.3.jar
constituent[29]: file:/home/username/opt/apache-maven-3.2.3/lib/slf4j-api-1.7.5.jar
constituent[30]: file:/home/username/opt/apache-maven-3.2.3/lib/plexus-cipher-1.7.jar
constituent[31]: file:/home/username/opt/apache-maven-3.2.3/lib/wagon-http-2.6-shaded.jar
constituent[32]: file:/home/username/opt/apache-maven-3.2.3/lib/plexus-component-annotations-1.5.5.jar
constituent[33]: file:/home/username/opt/apache-maven-3.2.3/lib/wagon-provider-api-2.6.jar
constituent[34]: file:/home/username/opt/apache-maven-3.2.3/lib/plexus-sec-dispatcher-1.3.jar
constituent[35]: file:/home/username/opt/apache-maven-3.2.3/lib/plexus-interpolation-1.19.jar
constituent[36]: file:/home/username/opt/apache-maven-3.2.3/lib/maven-embedder-3.2.3.jar
constituent[37]: file:/home/username/opt/apache-maven-3.2.3/lib/maven-core-3.2.3.jar
constituent[38]: file:/home/username/opt/apache-maven-3.2.3/lib/jsoup-1.7.2.jar
constituent[39]: file:/home/username/opt/apache-maven-3.2.3/lib/commons-lang-2.6.jar
constituent[40]: file:/home/username/opt/apache-maven-3.2.3/lib/maven-artifact-3.2.3.jar
constituent[41]: file:/home/username/opt/apache-maven-3.2.3/lib/wagon-http-shared-2.6.jar
constituent[42]: file:/home/username/opt/apache-maven-3.2.3/conf/logging/
---------------------------------------------------
java.util.EmptyStackException
	at java.util.Stack.peek(Stack.java:102)
	at org.apache.logging.log4j.core.impl.ThrowableProxy.resolvePackageData(ThrowableProxy.java:339)
	at org.apache.logging.log4j.core.impl.ThrowableProxy.<init>(ThrowableProxy.java:71)
	at org.apache.logging.log4j.core.impl.Log4jLogEvent.<init>(Log4jLogEvent.java:110)
	at org.apache.logging.log4j.core.impl.Log4jLogEvent.<init>(Log4jLogEvent.java:81)
	at org.apache.logging.log4j.core.config.LoggerConfig.createEvent(LoggerConfig.java:423)
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:344)
	at org.apache.logging.log4j.core.Logger.log(Logger.java:110)
	at org.apache.logging.log4j.spi.AbstractLoggerWrapper.log(AbstractLoggerWrapper.java:55)
	at org.slf4j.impl.SLF4JLogger.error(SLF4JLogger.java:427)
	at org.apache.maven.cli.CLIReportingUtils.showError(CLIReportingUtils.java:133)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:233)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)

**Comment by red61wjt** [comment]
I don't get this error with maven 3.3.9
