### ISSUE TITLE
Issues with Lombok Annotations

### ISSUE THREAD

**Issue by hypery2k** [raphaeljolivet/java2typescript#59]
We're using Lombok Annotations and getting errors when using the Jackson module:

```
Exception in thread "main" java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.introspect.AnnotatedMethod.<init>(Lcom/fasterxml/jackson/databind/introspect/AnnotatedClass;Ljava/lang/reflect/Method;Lcom/fasterxml/jackson/databind/introspect/AnnotationMap;[Lcom/fasterxml/jackson/databind/introspect/AnnotationMap;)V
    at java2typescript.jackson.module.visitors.TSJsonObjectFormatVisitor.addMethod(TSJsonObjectFormatVisitor.java:119)
    at java2typescript.jackson.module.visitors.TSJsonObjectFormatVisitor.addPublicMethods(TSJsonObjectFormatVisitor.java:99)
    at java2typescript.jackson.module.visitors.TSJsonFormatVisitorWrapper.useNamedClassOrParse(TSJsonFormatVisitorWrapper.java:87)
    at java2typescript.jackson.module.visitors.TSJsonFormatVisitorWrapper.expectObjectFormat(TSJsonFormatVisitorWrapper.java:112)
    at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.acceptJsonFormatVisitor(BeanSerializerBase.java:809)
    at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.acceptJsonFormatVisitor(DefaultSerializerProvider.java:580)
    at com.fasterxml.jackson.databind.ObjectMapper.acceptJsonFormatVisitor(ObjectMapper.java:3641)
    at com.fasterxml.jackson.databind.ObjectMapper.acceptJsonFormatVisitor(ObjectMapper.java:3620)
    at java2typescript.jackson.module.DefinitionGenerator.generateTypeScript(DefinitionGenerator.java:54)
```

Any ideas?

**Comment by atsu85** [comment]
I'm using Lombok myself without any issues - from the stack trace I'd guess that You have incompatible jackson version in Your runtime classpath. Take compare Your version to what is used by java2typescript-jackson

**Comment by atsu85** [comment]
no response - closing

**Comment by hypery2k** [comment]
sorry about me lack of a response. The Jackson version mismatch was the issue

**Comment by atsu85** [comment]
thanks for the reply :)
