### ISSUE TITLE
Convert `List<SomeType>` to `SomeType[]`

### ISSUE THREAD

**Issue by andyperlitch** [raphaeljolivet/java2typescript#78]
@atsu85  Is there a way to achieve this now? Currently I am getting the following error:

```
Exception in thread "main" java.lang.RuntimeException: Error when serializing interface java.util.List, you should add a custom mapping for it
	at java2typescript.jackson.module.visitors.TSJsonObjectFormatVisitor.getTSTypeForProperty(TSJsonObjectFormatVisitor.java:180)
	at java2typescript.jackson.module.visitors.TSJsonObjectFormatVisitor.optionalProperty(TSJsonObjectFormatVisitor.java:144)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.depositSchemaProperty(BeanPropertyWriter.java:816)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.acceptJsonFormatVisitor(BeanSerializerBase.java:833)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.acceptJsonFormatVisitor(DefaultSerializerProvider.java:580)
	at com.fasterxml.jackson.databind.ObjectMapper.acceptJsonFormatVisitor(ObjectMapper.java:3650)
	at com.fasterxml.jackson.databind.ObjectMapper.acceptJsonFormatVisitor(ObjectMapper.java:3629)
	at java2typescript.jackson.module.DefinitionGenerator.generateTypeScript(DefinitionGenerator.java:54)
	at com.cisco.candid.App.createModule(App.java:119)
	at com.cisco.candid.App.generateTypescript(App.java:105)
	at com.cisco.candid.App.main(App.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.lang.RuntimeException: Error when serializing interface java.util.List, you should add a custom mapping for it
	at java2typescript.jackson.module.visitors.TSJsonObjectFormatVisitor.getTSTypeForProperty(TSJsonObjectFormatVisitor.java:180)
	at java2typescript.jackson.module.visitors.TSJsonObjectFormatVisitor.optionalProperty(TSJsonObjectFormatVisitor.java:144)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.depositSchemaProperty(BeanPropertyWriter.java:816)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.acceptJsonFormatVisitor(BeanSerializerBase.java:833)
	at java2typescript.jackson.module.visitors.TSJsonArrayFormatVisitor.itemsFormat(TSJsonArrayFormatVisitor.java:42)
	at com.fasterxml.jackson.databind.ser.std.StdSerializer.visitArrayFormat(StdSerializer.java:277)
	at com.fasterxml.jackson.databind.ser.std.AsArraySerializerBase.acceptJsonFormatVisitor(AsArraySerializerBase.java:302)
	at java2typescript.jackson.module.visitors.TSJsonFormatVisitorWrapper.getTSTypeForHandler(TSJsonFormatVisitorWrapper.java:66)
	at java2typescript.jackson.module.visitors.TSJsonObjectFormatVisitor.getTSTypeForProperty(TSJsonObjectFormatVisitor.java:174)
	... 15 more
```

I see some info in the readme regarding mapping types, but I don't know how to handle types which have type arguments.

**Comment by andyperlitch** [comment]
whoops, nevermind, this was getting caused by another error. Please ignore!
